### ISSUE TITLE
0.3.0 crashes with farmersdelight

### ISSUE THREAD

**Issue by Rad586** [TheComputerizer/The-Impossible-Library#12]
**Game:** 1.18.2 with Fabric Loader 0.14.21
**Environment:** 
- fabricloader 0.14.21
- farmersdelight 1.18.2-1.2.5
- java 20
- minecraft 1.18.2
- theimpossiblelibrary 1.18.2-fabric-0.3.0
**Log:** 
https://gist.github.com/Rad233/2d773d48878105fa58754626993f0b73

**Comment by TheComputerizer** [comment]
It seems I may have forgotten to double check the mixin refmap was getting generated properly in the fabric versions

**Comment by TheComputerizer** [comment]
Fixed in 0.3.1
