### ISSUE TITLE
Not loading on server-side

### ISSUE THREAD

**Issue by whitemediator** [TheComputerizer/The-Impossible-Library#13]
The newest version for 1.19.2 till these time and date doesn't load on server side, so there is an error of mismatching mods when trying to join basically asking the player for client-side deletion or the mod getting added to server-side, even though is already on the server, kind regards.

**Comment by TheComputerizer** [comment]
Is this the forge or fabric version

**Comment by whitemediator** [comment]
This is forge

**Comment by whitemediator** [comment]
theimpossiblelibrary-1.19.2-0.3.0.jar to be precise, again ty for everything and sorry for the trouble, kind regards

**Comment by TheComputerizer** [comment]
Fixed in 0.3.1
