### ISSUE TITLE
Crash on 1.12.2-0.3.0

### ISSUE THREAD

**Issue by R3TR0xSN1P3R** [TheComputerizer/The-Impossible-Library#14]
problem when joining a server i get
[crash-2023-10-05_13.55.10-client.txt](https://github.com/TheComputerizer/The-Impossible-Library/files/12826051/crash-2023-10-05_13.55.10-client.txt)

the only error it throws is this
java.lang.NoClassDefFoundError: mods/thecomputerizer/theimpossiblelibrary/client/render/Renderable

**Comment by TheComputerizer** [comment]
There seems to be a bunch of mods working together for a big mess of a conflict, but see if updating [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files?page=1&pageSize=20&version=1.12.2) and [RedCore](https://www.curseforge.com/minecraft/mc-mods/red-core/files?page=1&pageSize=20&version=1.12.2) fixes it

**Comment by TheComputerizer** [comment]
Yeah so my last comment was completely wrong. I figured it out and put the full explanation here https://github.com/TheComputerizer/Music-Triggers/issues/158#issuecomment-2075391878

**Comment by TheComputerizer** [comment]
Since this is not actually an issue with this mod I will also be closing it here
