### ISSUE TITLE
Game crashes upon starting up (1.12.2)

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [TheComputerizer/The-Impossible-Library#5]
Here's the error:
Error: java.lang.NoSuchMethodError: mods.thecomputerizer.theimpossiblelibrary.util.file.TomlUtil.readIfExists(Lcom/moandjiezana/toml/Toml;Ljava/lang/String;Z)Z

**Comment by SlytherTheUndertaker** [comment]
..Oh, and here's the crash report: https://pastebin.com/R0Wtg2t2

**Comment by TheComputerizer** [comment]
The beta version of music triggers 6.0 isnt compatible with 0.2.0 of this one. You need 0.1.9
